### ISSUE TITLE
Powering the module

### ISSUE THREAD

**Issue by Terbijn** [TomWhitwell/Magnetophon#7]
Hi,

I'm putting together an installation and don't have a proper Eurorack power supply at hand right now. Do you think the module could be powered with batteries? If so, is there something you recommend? The exhibition would be on for 7 days and I think the module would be in active use for not more than 3 hours during that time. 
Also, are there instructions for building the wand? 

Thank you very much!

Best wishes,
Oliver

**Comment by TomWhitwell** [comment]
I've never tried it, but you might be able to use two 9v batteries back to back
